### PR TITLE
Ability to limit default setting to a single cid

### PR DESCRIPTION
**Pull request by julianlam**
As on tin :trollface:

### CODE REVIEW

**Comment by julianlam** [comment]
Also updated to new ACP design.

**Comment by jeffbski** [comment]
I like the idea behind being able to restrict which categories default to Q/A, however I would prefer to be able to select multiple categories, not just one. I think Q/A is an awesome feature but due to the way the interface works, many users will not know how to use it, so defaulting is a great idea, but I would want to do that for many categories.

I would envision many categories being Q/A and then others defaulting to normal posts.

Also I tried the branch for this pull request and it didn't seem to work. The category I selected to limit the default to didn't change the submit button to "ask question".

**Comment by psychobunny** [comment]
Thanks for the PR @julianlam do you know if you can solve 

> Also I tried the branch for this pull request and it didn't seem to work. The category I selected to limit the default to didn't change the submit button to "ask question".

**Comment by julianlam** [comment]
Hey @psychobunny, when I made the PR, I did test to ensure that it worked to limit the `makeDefault` option to a single category

**Comment by julianlam** [comment]
As it's a client side config, you don't even need a restart/reload

**Comment by julianlam** [comment]
Confirmed working.

**Comment by julianlam** [comment]
ping @psychobunny :smile:

**Pull request merged**
